const KEY="mithraq_v2_groupwise";
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{chits:[],members:[],auctions:[],payments:[]};
// Migrate old MithraQ data if it exists.
if(!state.chits.length && !state.members.length){try{const old=JSON.parse(localStorage.getItem('mithraq_v1')||'null');if(old)state=old;}catch(e){}}
state.chits=Array.isArray(state.chits)?state.chits:[]; state.members=Array.isArray(state.members)?state.members:[];
state.auctions=Array.isArray(state.auctions)?state.auctions:[]; state.payments=Array.isArray(state.payments)?state.payments:[];
let tab="home";
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function money(n){return "₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2});}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function chitById(id){return state.chits.find(c=>String(c.id)===String(id));}
function membersForChit(id){return state.members.filter(m=>(m.chitIds||[]).map(String).includes(String(id)));}
function render(){const app=document.getElementById("app"); if(tab==='home')app.innerHTML=home(); if(tab==='chits')app.innerHTML=chits(); if(tab==='members')app.innerHTML=members(); if(tab==='auction')app.innerHTML=auction(); if(tab==='reports')app.innerHTML=reports(); document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));}
function home(){const total=state.chits.reduce((s,c)=>s+Number(c.amount||0),0),col=state.payments.reduce((s,p)=>s+Number(p.amount||0),0);return `<h2 class="page-title">Good day 👋</h2><div class="subtitle">MithraQ • Smart Chit Management</div><div class="hero"><small>♛ TOTAL CHIT PORTFOLIO</small><h2>${money(total)}</h2><div class="muted hero-muted">Track collections, members, auctions and dividends from one place.</div></div><div class="grid"><div class="card"><div class="stat-label">ACTIVE CHITS</div><div class="stat-value">${state.chits.length}</div></div><div class="card"><div class="stat-label">MEMBERS</div><div class="stat-value">${state.members.length}</div></div><div class="card"><div class="stat-label">COLLECTED</div><div class="stat-value">${money(col)}</div></div><div class="card"><div class="stat-label">PENDING</div><div class="stat-value">${money(Math.max(0,total-col))}</div></div></div><div class="section"><h3>Quick Actions</h3><span class="muted">Together We Grow</span></div><div class="quick-grid"><button class="quick" onclick="newChit()"><b>＋</b><span>New Chit</span></button><button class="quick" onclick="newMember()"><b>♙</b><span>Member</span></button><button class="quick" onclick="tab='auction';render()"><b>₹</b><span>Collection</span></button></div><div class="section"><h3>Recent Activity</h3></div><div class="empty recent">No transactions yet.</div>`;}
function chits(){return `<div class="row"><div><h2 class="page-title">Chits</h2><div class="subtitle">Create groups first, then add members to a selected group.</div></div><button class="btn gold" onclick="newChit()">+ New Chit</button></div><div class="list">${state.chits.length?state.chits.map(c=>{const n=membersForChit(c.id).length;return `<div class="card chit-card"><div class="row"><div><div class="chit-title">${esc(c.name)}</div><div class="muted">${money(c.amount)} · ${c.duration||0} months · ${c.type==='dividend'?'Dividend':'Fixed'}</div></div><span class="badge active">${n} MEMBERS</span></div><div class="progress"><i style="width:${Math.min(100,(c.current||0)/(c.duration||1)*100)}%"></i></div><div class="muted">Monthly ${money(c.monthly||0)} · ${c.current||0}/${c.duration||0} months</div><button class="small-link" onclick="openGroupMembers('${c.id}')">View ${n} group members →</button></div>`}).join(''):'<div class="empty">No chits yet.<br><br><button class="btn gold" onclick="newChit()">Create your first chit</button></div>'}</div>`;}
function newChit(){openModal('Create New Chit',`<div class="form"><input id="fName" placeholder="Chit name"><input id="fAmount" type="number" placeholder="Total amount ₹"><input id="fDuration" type="number" placeholder="Duration (months)"><select id="fType"><option value="fixed">Fixed Chit</option><option value="dividend">Dividend Chit</option></select><input id="fCommission" type="number" placeholder="Commission % (optional)"><button class="btn gold full" onclick="createChit()">Create Chit</button></div>`);}
function createChit(){const name=document.getElementById('fName').value.trim(),amount=Number(document.getElementById('fAmount').value),duration=Number(document.getElementById('fDuration').value),type=document.getElementById('fType').value,commission=Number(document.getElementById('fCommission').value||0);if(!name||!amount||!duration)return alert('Please enter chit name, amount and duration.');state.chits.push({id:Date.now(),name,amount,duration,current:0,monthly:amount/duration,type,commission});save();closeModal();render();}
function members(){if(!state.chits.length)return `<div class="row"><div><h2 class="page-title">Members</h2><div class="subtitle">Create a chit group first.</div></div></div><div class="empty big-empty"><div class="empty-icon">♙</div><b>No chit groups available</b><p>Add a chit first. Members will be added <strong>group-wise</strong> only to the chit you select.</p><button class="btn gold" onclick="newChit()">+ Create Chit</button></div>`;return `<div class="row"><div><h2 class="page-title">Members</h2><div class="subtitle">${state.members.length} registered members • Group wise</div></div><button class="btn gold" onclick="newMember()">+ Add</button></div><div class="group-tabs">${state.chits.map((c,i)=>`<button class="group-pill ${i===0?'selected':''}" onclick="showGroup('${c.id}',this)">${esc(c.name)} <b>${membersForChit(c.id).length}</b></button>`).join('')}</div><div id="groupMembers">${groupMemberPanel(state.chits[0].id)}</div>`;}
function groupMemberPanel(id){const c=chitById(id),list=membersForChit(id);return `<div class="group-head"><div><h3>${esc(c.name)}</h3><span>${c.type==='dividend'?'Dividend':'Fixed'} • Monthly ${money(c.monthly||0)}</span></div><span class="badge active">${list.length} MEMBERS</span></div><div class="list">${list.length?list.map(m=>`<div class="card member"><div class="avatar">${esc((m.name||'?')[0]).toUpperCase()}</div><div style="flex:1"><div class="chit-title">${esc(m.name)}</div><div class="muted">${esc(m.phone||'No phone')} • Member #${esc(m.memberNo||'—')}</div><div class="muted">Joined ${esc(m.joiningDate||'—')} • Monthly ${money(m.monthly||c.monthly||0)}</div></div><span class="badge active">ACTIVE</span></div>`).join(''):'<div class="empty">No members in this chit yet.<br><br><button class="btn gold" onclick="newMember('${c.id}')">+ Add member to ${esc(c.name)}</button></div>'}</div>`;}
function showGroup(id,el){document.querySelectorAll('.group-pill').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');document.getElementById('groupMembers').innerHTML=groupMemberPanel(id);}
function openGroupMembers(id){tab='members';render();setTimeout(()=>{const btn=[...document.querySelectorAll('.group-pill')].find(x=>x.textContent.trim().startsWith(chitById(id)?.name||'§'));if(btn)showGroup(id,btn);},0);}
function newMember(preselect=''){if(!state.chits.length)return alert('Please create a chit group first.');openModal('Add Member — Select Chit Group',`<div class="form"><label class="field-label">Chit Group <span>*</span></label><select id="mChit">${state.chits.map(c=>`<option value="${c.id}" ${String(c.id)===String(preselect)?'selected':''}>${esc(c.name)} • ${c.type==='dividend'?'Dividend':'Fixed'} • ${money(c.monthly||0)}/month</option>`).join('')}</select><label class="field-label">Member details</label><input id="mName" placeholder="Member name"><input id="mPhone" type="tel" placeholder="Phone number"><input id="mNo" placeholder="Member number (optional)"><input id="mDate" type="date" value="${new Date().toISOString().slice(0,10)}"><input id="mMonthly" type="number" placeholder="Monthly amount ₹ (optional)"><button class="btn gold full" onclick="createMember()">Add to Selected Chit</button><div class="form-note">Only members added to the selected chit will appear in that group, and only those members can be used for that group's auction.</div></div>`);}
function createMember(){const chitId=document.getElementById('mChit').value,name=document.getElementById('mName').value.trim();if(!name)return alert('Enter member name.');const c=chitById(chitId),monthly=Number(document.getElementById('mMonthly').value||c.monthly||0);state.members.push({id:Date.now(),name,phone:document.getElementById('mPhone').value.trim(),memberNo:document.getElementById('mNo').value.trim(),joiningDate:document.getElementById('mDate').value,chitIds:[chitId],monthly});save();closeModal();tab='members';render();setTimeout(()=>{const btn=document.querySelector('.group-pill'); if(btn)showGroup(chitId,[...document.querySelectorAll('.group-pill')].find(x=>x.textContent.trim().startsWith(c.name))||btn)},0);}
function auction(){if(!state.chits.length)return `<h2 class="page-title">Auction Room</h2><div class="subtitle">Select a chit group first.</div><div class="empty big-empty"><b>No chit groups available</b><p>Create a chit before starting an auction.</p><button class="btn gold" onclick="newChit()">+ Create Chit</button></div>`;const c=state.chits[0],ms=membersForChit(c.id);return `<h2 class="page-title">Auction Room</h2><div class="subtitle">Only members belonging to the selected group can bid.</div><div class="card"><div class="section no-margin"><h3>Live Auction Entry</h3><span class="badge pending">READY</span></div><div class="form"><label class="field-label">Chit Group</label><select id="auctionChit" onchange="renderAuctionMembers()">${state.chits.map(x=>`<option value="${x.id}">${esc(x.name)} • ${x.type==='dividend'?'Dividend':'Fixed'}</option>`).join('')}</select><div id="auctionMembers">${auctionMemberSelect(ms)}</div><input id="bid" type="number" placeholder="Bid / auction discount ₹"><div class="timer-card"><div><span>ROUND</span><strong id="roundNo">1</strong> <small>/ 3</small></div><div id="timer">00:30</div><button class="timer-btn" onclick="startAuctionTimer()">START</button></div><button class="btn gold full" onclick="saveAuction()">Confirm Bid / Winner</button></div></div><div class="section"><h3>Auction History</h3></div><div class="list">${state.auctions.map(a=>`<div class="card row"><div><b>${esc(a.chit)}</b><div class="muted">${esc(a.member||'')} • ${esc(a.round||'Final')} • ${a.date}</div></div><b>${money(a.bid)}</b></div>`).join('')||'<div class="empty">No auctions recorded.</div>'}</div>`;}
function auctionMemberSelect(ms){return `<select id="auctionMember">${ms.length?ms.map(m=>`<option value="${m.id}">${esc(m.name)} • #${esc(m.memberNo||'—')}</option>`).join(''):'<option value="">No members in this group</option>'}</select><div class="form-note">${ms.length} member(s) available for this chit only.</div>`;}
function renderAuctionMembers(){const c=chitById(document.getElementById('auctionChit').value);document.getElementById('auctionMembers').innerHTML=auctionMemberSelect(membersForChit(c.id));}
let timer=null,seconds=30,round=1;
function startAuctionTimer(){clearInterval(timer);seconds=30;document.getElementById('roundNo').textContent=round;document.getElementById('timer').textContent='00:30';timer=setInterval(()=>{seconds--;document.getElementById('timer').textContent='00:'+String(seconds).padStart(2,'0');if(seconds<=0){clearInterval(timer);if(round<3){round++;alert('Round '+(round-1)+' complete. Starting Round '+round+'.');document.getElementById('roundNo').textContent=round;document.getElementById('timer').textContent='00:30';startAuctionTimer();}else{alert('Final Round complete. Select the winner and confirm bid.');round=1;} }},1000);}
function saveAuction(){const c=chitById(document.getElementById('auctionChit')?.value),mid=document.getElementById('auctionMember')?.value,bid=Number(document.getElementById('bid')?.value||0);if(!c||!mid||!bid)return alert('Select a group/member and enter bid amount.');const m=state.members.find(x=>String(x.id)===String(mid));state.auctions.unshift({id:Date.now(),chit:c.name,chitId:c.id,member:m?.name||'',memberId:mid,bid,round:'Round '+round,date:new Date().toLocaleDateString('en-IN')});save();render();}
function reports(){const col=state.payments.reduce((s,p)=>s+Number(p.amount||0),0);return `<h2 class="page-title">Reports</h2><div class="subtitle">Group-wise overview</div><div class="grid"><div class="card"><div class="stat-label">CHITS</div><div class="stat-value">${state.chits.length}</div></div><div class="card"><div class="stat-label">MEMBERS</div><div class="stat-value">${state.members.length}</div></div><div class="card"><div class="stat-label">COLLECTION</div><div class="stat-value">${money(col)}</div></div><div class="card"><div class="stat-label">AUCTIONS</div><div class="stat-value">${state.auctions.length}</div></div></div>${state.chits.map(c=>`<div class="card report-group"><div class="row"><b>${esc(c.name)}</b><span class="badge active">${membersForChit(c.id).length} MEMBERS</span></div><div class="muted">${c.type==='dividend'?'Dividend':'Fixed'} • Monthly ${money(c.monthly||0)} • Auctions ${state.auctions.filter(a=>String(a.chitId)===String(c.id)).length}</div></div>`).join('')}`;}
function openModal(title,body){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=body;document.getElementById('modal').classList.remove('hidden');}
function closeModal(){document.getElementById('modal').classList.add('hidden');}
document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal();});
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});
render();
