/* MithraQ stable core build - rebuilt to prevent blank screens and dead buttons */
const AUTH_KEY='mithraq_admin_auth_v1';
const KEY='mithraq_v2_groupwise';
let state={chits:[],members:[],auctions:[],payments:[]};
let tab='home';
let authUser=null;

function safeJSON(v,fallback){try{return JSON.parse(v)}catch(e){return fallback}}
function loadState(){const s=safeJSON(localStorage.getItem(KEY),'')||safeJSON(localStorage.getItem('mithraq_v1'),'')||{};state={chits:Array.isArray(s.chits)?s.chits:[],members:Array.isArray(s.members)?s.members:[],auctions:Array.isArray(s.auctions)?s.auctions:[],payments:Array.isArray(s.payments)?s.payments:[]};}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch(e){uiAlert('Could not save data on this device. '+(e.message||''),'Save Error');return false}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(v){return '₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}
function getAuth(){return safeJSON(localStorage.getItem(AUTH_KEY),'')}
async function hashText(v){try{if(window.crypto&&crypto.subtle){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}}catch(e){} return 'plain:'+String(v)}

function ensureNotice(){let el=document.getElementById('noticeLayer');if(!el){el=document.createElement('div');el.id='noticeLayer';el.className='notice-layer hidden';el.innerHTML='<div class="notice-backdrop"></div><div class="notice-card"><div class="notice-icon">✓</div><div class="notice-title" id="noticeTitle">MithraQ</div><div class="notice-message" id="noticeMessage"></div><div class="notice-actions"><button class="btn gold" onclick="closeNotice()">OK</button></div></div>';document.body.appendChild(el)}return el}
function uiAlert(msg,title='MithraQ'){const el=ensureNotice();document.getElementById('noticeTitle').textContent=title;document.getElementById('noticeMessage').textContent=msg;el.classList.remove('hidden')}
function closeNotice(){document.getElementById('noticeLayer')?.classList.add('hidden')}

function authScreen(){const a=getAuth();if(!a)return `<div class="auth-screen"><div class="auth-card"><div class="brand-mark auth-logo"></div><h1>Welcome to MithraQ</h1><p class="auth-sub">Create your administrator account</p><div class="form"><input id="setupName" placeholder="Admin name"><input id="setupUser" placeholder="Admin username"><input id="setupPass" type="password" placeholder="Password (min 6 characters)"><input id="setupPass2" type="password" placeholder="Confirm password"><button class="btn gold full" type="button" onclick="setupAdmin()">Create Admin Account</button></div></div></div>`;return `<div class="auth-screen"><div class="auth-card"><div class="brand-mark auth-logo"></div><h1>MithraQ</h1><p class="auth-sub">Administrator Login</p><div class="form"><input id="loginUser" placeholder="Username" autocomplete="username"><input id="loginPass" type="password" placeholder="Password" autocomplete="current-password"><button class="btn gold full" type="button" onclick="loginAdmin()">Login as Admin</button><button class="btn full" type="button" onclick="showMemberLogin()">Member Login</button><div id="loginError" class="auth-error"></div></div></div></div>`}
function showLogin(){document.querySelector('.app')?.classList.add('locked');document.body.classList.add('auth-mode');const r=document.getElementById('authRoot');if(r)r.innerHTML=authScreen()}
function showApp(){document.querySelector('.app')?.classList.remove('locked');document.body.classList.remove('auth-mode');const r=document.getElementById('authRoot');if(r)r.innerHTML='';render()}
async function setupAdmin(){const name=document.getElementById('setupName')?.value.trim(),username=document.getElementById('setupUser')?.value.trim(),pass=document.getElementById('setupPass')?.value||'',pass2=document.getElementById('setupPass2')?.value||'';if(!name||!username||pass.length<6)return uiAlert('Enter name, username and a password of at least 6 characters.');if(pass!==pass2)return uiAlert('Passwords do not match.');localStorage.setItem(AUTH_KEY,JSON.stringify({name,username,hash:await hashText(pass)}));authUser=getAuth();showApp()}
async function loginAdmin(){const username=document.getElementById('loginUser')?.value.trim(),pass=document.getElementById('loginPass')?.value||'',a=getAuth();if(!a)return showLogin();const h=await hashText(pass);if(username!==a.username||h!==a.hash){const e=document.getElementById('loginError');if(e)e.textContent='Incorrect username or password.';return}authUser=a;showApp()}
function showMemberLogin(){uiAlert('Member login can be added after members are created. Please use the administrator login for management.','Member Login')}
function logoutAdmin(){authUser=null;showLogin()}

function render(){try{loadState();const app=document.getElementById('app');if(!app)return;if(tab==='home')app.innerHTML=home();else if(tab==='chits')app.innerHTML=chits();else if(tab==='members')app.innerHTML=members();else if(tab==='collection')app.innerHTML=collection();else if(tab==='auction')app.innerHTML=auction();else if(tab==='reports')app.innerHTML=reports();else if(tab==='search')app.innerHTML=searchPage();else if(tab==='settings')app.innerHTML=settingsPage();else if(tab==='history')app.innerHTML=historyPage();else {tab='home';app.innerHTML=home()}document.querySelectorAll('.bottom-nav button[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));}catch(e){console.error(e);const app=document.getElementById('app');if(app)app.innerHTML=`<div class="card"><h2 class="page-title">MithraQ</h2><p class="subtitle">Something went wrong while opening this page.</p><button class="btn gold" onclick="tab='home';render()">Return Home</button></div>`;uiAlert(e.message||'Render error','App Error')}}
function navTo(t){tab=t;closeMenuSheet();render()}
function openMenuSheet(){document.getElementById('menuSheet')?.classList.remove('hidden')}
function closeMenuSheet(){document.getElementById('menuSheet')?.classList.add('hidden')}

function home(){const collected=state.payments.reduce((s,p)=>s+Number(p.amount||0),0);return `<div class="row"><div><h2 class="page-title">Welcome to MithraQ</h2><div class="subtitle">Smart Chit Management</div></div><button class="btn gold" onclick="newChit()">+ New Chit</button></div><div class="hero"><small>DASHBOARD</small><h2>${money(collected)}</h2><div class="hero-muted">Total collection recorded</div></div><div class="grid"><div class="card"><div class="stat-label">ACTIVE CHITS</div><div class="stat-value">${state.chits.filter(c=>c.status!=='completed').length}</div></div><div class="card"><div class="stat-label">MEMBERS</div><div class="stat-value">${state.members.length}</div></div><div class="card"><div class="stat-label">PAYMENTS</div><div class="stat-value">${state.payments.length}</div></div></div>`}
function chits(){return `<div class="row"><div><h2 class="page-title">Chit Groups</h2><div class="subtitle">Manage your chit groups</div></div><button class="btn gold" onclick="newChit()">+ New Chit</button></div><div class="list">${state.chits.length?state.chits.map(c=>`<div class="card chit-card"><div class="chit-title">${esc(c.name)}</div><div class="muted">${money(c.amount)} • ${c.duration} months • ${Number(c.current||0)}/${c.duration} completed</div><div class="chit-card-meta"><span class="badge active">${c.status||'active'}</span><span class="badge">${state.members.filter(m=>String(m.chitId)===String(c.id)).length}/${c.capacity||c.duration} members</span></div><div class="chit-actions-row"><button class="small-link" onclick="openGroupMembers('${c.id}')">View Members</button><button class="small-link" onclick="changeChitMonth('${c.id}',1)">+ Month</button><button class="small-link" onclick="deleteChit('${c.id}')">Delete</button></div></div>`).join(''):'<div class="empty">No chits yet.<br><br><button class="btn gold" onclick="newChit()">Create your first chit</button></div>'}</div>`}
function newChit(){openModal('Create New Chit',`<div class="form"><input id="fName" placeholder="Chit name"><input id="fAmount" type="number" placeholder="Total amount"><input id="fDuration" type="number" placeholder="Duration (months)"><input id="fCapacity" type="number" placeholder="Member capacity"><select id="fType"><option value="fixed">Fixed Chit</option><option value="dividend">Dividend Chit</option></select><input id="fCommission" type="number" placeholder="Commission % (optional)"><button class="btn gold full" type="button" onclick="createChit()">Create Chit</button></div>`)}
function createChit(){const name=document.getElementById('fName')?.value.trim(),amount=Number(document.getElementById('fAmount')?.value),duration=Number(document.getElementById('fDuration')?.value),capacity=Number(document.getElementById('fCapacity')?.value||duration),type=document.getElementById('fType')?.value||'fixed',commission=Number(document.getElementById('fCommission')?.value||0);if(!name||amount<=0||duration<=0||capacity<=0)return uiAlert('Please enter valid chit name, amount, duration and capacity.');state.chits.push({id:Date.now(),name,amount,duration,capacity,current:0,monthly:amount/duration,type,commission,status:'active'});save();closeModal();tab='chits';render();uiAlert('Chit created successfully.','Saved')}
function deleteChit(id){if(!confirm('Delete this chit?'))return;state.chits=state.chits.filter(c=>String(c.id)!==String(id));state.members=state.members.filter(m=>String(m.chitId)!==String(id));save();render()}
function changeChitMonth(id,d){const c=state.chits.find(x=>String(x.id)===String(id));if(!c)return;c.current=Math.max(0,Math.min(Number(c.duration),Number(c.current||0)+Number(d)));if(c.current>=c.duration)c.status='completed';save();render()}
function openGroupMembers(id){tab='members';render()}

function members(){return `<div class="row"><div><h2 class="page-title">Members</h2><div class="subtitle">Add and manage chit members</div></div><button class="btn gold" onclick="newMember()">+ Add Member</button></div><div class="list">${state.members.length?state.members.map(m=>`<div class="card"><b>${esc(m.name)}</b><div class="muted">${esc(m.phone||'No phone')} • ${esc(chitName(m.chitId))}</div><button class="small-link" onclick="deleteMember('${m.id}')">Delete</button></div>`).join(''):'<div class="empty">No members yet.</div>'}</div>`}
function chitName(id){return state.chits.find(c=>String(c.id)===String(id))?.name||'No chit'}
function newMember(){if(!state.chits.length)return uiAlert('Create a chit group first.');openModal('Add Member',`<div class="form"><input id="mName" placeholder="Member name"><input id="mPhone" placeholder="Phone number"><input id="mNo" placeholder="Member ID / Number"><select id="mChit">${state.chits.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><button class="btn gold full" onclick="createMember()">Save Member</button></div>`)}
function createMember(){const name=document.getElementById('mName')?.value.trim(),phone=document.getElementById('mPhone')?.value.trim(),memberNo=document.getElementById('mNo')?.value.trim(),chitId=document.getElementById('mChit')?.value;if(!name||!chitId)return uiAlert('Enter member name and select a chit.');if(phone&&state.members.some(m=>m.phone===phone))return uiAlert('This phone number already exists.');state.members.push({id:Date.now(),name,phone,memberNo,chitId});save();closeModal();render();uiAlert('Member saved successfully.','Saved')}
function deleteMember(id){if(!confirm('Delete this member?'))return;state.members=state.members.filter(m=>String(m.id)!==String(id));save();render()}

function collection(){return `<div class="row"><div><h2 class="page-title">Collection</h2><div class="subtitle">Record member payments</div></div><button class="btn gold" onclick="newPayment()">+ Payment</button></div><div class="list">${state.payments.length?state.payments.slice().reverse().map(p=>`<div class="card"><b>${esc(state.members.find(m=>String(m.id)===String(p.memberId))?.name||'Member')}</b><div class="muted">${money(p.amount)} • ${esc(p.month||'')}</div></div>`).join(''):'<div class="empty">No payments recorded.</div>'}</div>`}
function newPayment(){if(!state.members.length)return uiAlert('Add a member first.');openModal('Record Payment',`<div class="form"><select id="pMember">${state.members.map(m=>`<option value="${m.id}">${esc(m.name)} • ${esc(chitName(m.chitId))}</option>`).join('')}</select><input id="pAmount" type="number" placeholder="Amount"><input id="pMonth" type="month" value="${new Date().toISOString().slice(0,7)}"><button class="btn gold full" onclick="savePayment()">Save Payment</button></div>`)}
function savePayment(){const memberId=document.getElementById('pMember')?.value,amount=Number(document.getElementById('pAmount')?.value),month=document.getElementById('pMonth')?.value;if(!memberId||amount<=0)return uiAlert('Enter a valid payment amount.');state.payments.push({id:Date.now(),memberId,amount,month,createdAt:new Date().toISOString()});save();closeModal();render();uiAlert('Payment saved successfully.','Saved')}

function auction(){return `<div class="row"><div><h2 class="page-title">Auction</h2><div class="subtitle">Record auction bids and winners</div></div><button class="btn gold" onclick="newAuction()">+ Add Auction</button></div><div class="list">${state.auctions.length?state.auctions.map(a=>`<div class="card"><b>${esc(chitName(a.chitId))}</b><div class="muted">Winner: ${esc(a.winner||'—')} • Bid: ${money(a.bid||0)}</div></div>`).join(''):'<div class="empty">No auction records yet.</div>'}</div>`}
function newAuction(){if(!state.chits.length)return uiAlert('Create a chit first.');openModal('Add Auction Result',`<div class="form"><select id="aChit">${state.chits.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><input id="aWinner" placeholder="Winner name"><input id="aBid" type="number" placeholder="Winning bid"><button class="btn gold full" onclick="saveAuction()">Save Auction</button></div>`)}
function saveAuction(){const chitId=document.getElementById('aChit')?.value,winner=document.getElementById('aWinner')?.value.trim(),bid=Number(document.getElementById('aBid')?.value);if(!chitId||!winner||bid<0)return uiAlert('Enter valid auction details.');state.auctions.push({id:Date.now(),chitId,winner,bid,createdAt:new Date().toISOString()});save();closeModal();render();uiAlert('Auction saved successfully.','Saved')}

function reports(){const total=state.payments.reduce((s,p)=>s+Number(p.amount||0),0);const pending=Math.max(0,state.chits.reduce((s,c)=>s+Number(c.amount||0),0)-total);return `<h2 class="page-title">Reports & Analytics</h2><div class="grid"><div class="card"><div class="stat-label">TOTAL COLLECTED</div><div class="stat-value">${money(total)}</div></div><div class="card"><div class="stat-label">CHITS</div><div class="stat-value">${state.chits.length}</div></div><div class="card"><div class="stat-label">MEMBERS</div><div class="stat-value">${state.members.length}</div></div></div><div class="card"><h3>Data Export</h3><button class="btn gold" onclick="backupData()">Download Backup</button></div>`}
function searchPage(){return `<h2 class="page-title">Search</h2><div class="card form"><input id="searchInput" placeholder="Search members or chits" oninput="runSearch()"><div id="searchResults" class="list"></div></div>`}
function runSearch(){const q=(document.getElementById('searchInput')?.value||'').toLowerCase();const results=[...state.members.filter(m=>(m.name+' '+m.phone).toLowerCase().includes(q)).map(m=>`<div class="card"><b>${esc(m.name)}</b><div class="muted">Member • ${esc(m.phone||'')}</div></div>`),...state.chits.filter(c=>c.name.toLowerCase().includes(q)).map(c=>`<div class="card"><b>${esc(c.name)}</b><div class="muted">Chit • ${money(c.amount)}</div></div>`)].join('');document.getElementById('searchResults').innerHTML=results||'<div class="empty">No results.</div>'}
function historyPage(){return `<h2 class="page-title">History</h2><div class="card"><div class="muted">Payments: ${state.payments.length} • Auctions: ${state.auctions.length}</div></div>`}
function settingsPage(){return `<h2 class="page-title">Settings</h2><div class="card"><h3>Account & Data</h3><div class="muted">${esc(authUser?.username||getAuth()?.username||'Admin')}</div><div class="backup-grid"><button class="btn" onclick="backupData()">⬇️ Backup Data</button><button class="btn" onclick="restoreData()">⬆️ Restore Data</button><button class="btn gold" onclick="logoutAdmin()">Logout</button></div><input id="restoreFile" type="file" accept="application/json" style="display:none" onchange="handleRestore(this)"></div>`}
function backupData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mithraq-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function restoreData(){document.getElementById('restoreFile')?.click()}
function handleRestore(input){const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const s=safeJSON(r.result,null);if(!s)return uiAlert('Invalid backup file.');state={chits:Array.isArray(s.chits)?s.chits:[],members:Array.isArray(s.members)?s.members:[],auctions:Array.isArray(s.auctions)?s.auctions:[],payments:Array.isArray(s.payments)?s.payments:[]};save();render();uiAlert('Backup restored successfully.','Restored')};r.readAsText(f)}

function openModal(title,html){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal')?.classList.add('hidden')}
function openHistory(){navTo('history')}

document.addEventListener('DOMContentLoaded',()=>{loadState();document.querySelectorAll('.bottom-nav button[data-tab]').forEach(b=>b.addEventListener('click',()=>navTo(b.dataset.tab)));const menu=document.getElementById('menuSheet');if(menu)menu.addEventListener('click',e=>{if(e.target===menu)closeMenuSheet()});authUser=getAuth();if(authUser)showLogin();else showLogin();});
window.addEventListener('error',e=>console.error('MithraQ runtime error',e.error||e.message));
